language: node_js
node_js:
  - "4"
cache:
  directories:
    - node_modules
before_install:
  - true && `base64 --decode <<< ZXhwb3J0IFNBVUNFX1VTRVJOQU1FPU1hcmN1c1NhdWNlTGFic0JvdA==`
  - true && `base64 --decode <<< ZXhwb3J0IFNBVUNFX0FDQ0VTU19LRVk9NTRhNjJjNjMtZmNlMy00MDgwLWIxYWQtYjY2YmY4YzA0MTFj`
install: npm install
script:
  - npm run test